### page 0
GET http://localhost:3000/users?page=0

### page -1
GET http://localhost:3000/users?page=-1

### page 6
GET http://localhost:3000/users?page=6


### No query params
GET http://localhost:3000/users

### page 1
GET http://localhost:3000/users?page=1

### page 2
GET http://localhost:3000/users?page=2

### page 3
GET http://localhost:3000/users?page=3

### page 4
GET http://localhost:3000/users?page=4

### page 5
GET http://localhost:3000/users?page=5